Triumers/KMS-Back

build.gradle, src/main/java/org/triumers/kmsback/auth/command/Application/controller/AuthController.java, src/main/java/org/triumers/kmsback/auth/command/Application/dto/AuthDTO.java, src/main/java/org/triumers/kmsback/auth/command/Application/service/AuthService.java, src/main/java/org/triumers/kmsback/auth/command/Application/service/AuthServiceImpl.java, src/main/java/org/triumers/kmsback/auth/command/domain/aggregate/entity/Auth.java, src/main/java/org/triumers/kmsback/auth/command/domain/aggregate/enums/UserRole.java, src/main/java/org/triumers/kmsback/auth/command/domain/aggregate/enums/UserRoleConverter.java, src/main/java/org/triumers/kmsback/auth/command/domain/aggregate/vo/CmdRequestAuthVO.java, src/main/java/org/triumers/kmsback/auth/command/domain/aggregate/vo/CmdResponseMessageVO.java, src/main/java/org/triumers/kmsback/auth/command/domain/repository/AuthRepository.java, src/main/java/org/triumers/kmsback/common/config/SecurityConfig.java, src/test/java/org/triumers/kmsback/auth/command/Application/service/AuthServiceTest.java
기본적인 회원가입 기능이 추가되었습니다.
추후 입력 값 검증 등에 대한 상세한 구현이 추가로 이루어질 예정입니다.
계정 생성 간 문제없이 정상적으로 계정 생성됨을 확인했습니다.
=> [Feature] 회원가입 기능 구현

src/main/resources/org/triumers/kmsback/post/query/repository/QryPostMapper.xml, src/test/java/org/triumers/kmsback/post/command/Application/service/CmdTabServiceTests.java, src/test/java/org/triumers/kmsback/post/query/service/QryPostServiceTest.java
- 탭에 따라 게시글 리스트 조회
- 단일 게시글 정보 및 태그 조회
- tab 테스트코드 수정
=> [Feature] 게시글 조회 관련 기능 및 TAB 테스트 수정

src/main/java/org/triumers/kmsback/common/auth/JwtFilter.java, src/main/java/org/triumers/kmsback/common/auth/JwtUtil.java, src/main/java/org/triumers/kmsback/common/auth/LoginFilter.java, src/main/java/org/triumers/kmsback/common/config/SecurityConfig.java
로그인 기능이 구현되었습니다.
email과 password를 이용해 로그인합니다.
로그인 성공 시 200 상태 코드와 함께 JWT 가 발급됩니다.
=> [Feature] 로그인 기능 구현

src/main/java/org/triumers/kmsback/quiz/command/Application/controller/CmdQuizController.java, src/main/java/org/triumers/kmsback/quiz/command/Application/dto/CmdQuizDTO.java, src/main/java/org/triumers/kmsback/quiz/command/Application/service/CmdQuizService.java, src/main/java/org/triumers/kmsback/quiz/command/Application/service/CmdQuizServiceImpl.java, src/main/java/org/triumers/kmsback/quiz/command/domain/aggregate/entity/CmdQuiz.java, src/main/java/org/triumers/kmsback/quiz/command/domain/aggregate/vo/CmdRequestQuizVo.java, src/main/java/org/triumers/kmsback/quiz/command/domain/aggregate/vo/CmdRequestRemoveQuizVo.java, src/main/java/org/triumers/kmsback/quiz/command/domain/aggregate/vo/CmdResponseMessageVO.java, src/main/java/org/triumers/kmsback/quiz/command/domain/repository/CmdQuizRepository.java, src/main/java/org/triumers/kmsback/quiz/query/aggregate/entity/QryAnswerSubmitter.java, src/main/java/org/triumers/kmsback/quiz/query/aggregate/entity/QryQuiz.java, src/main/java/org/triumers/kmsback/quiz/query/controller/QryAnswerSubmitterController.java, src/main/java/org/triumers/kmsback/quiz/query/controller/QryQuizController.java, src/main/java/org/triumers/kmsback/quiz/query/dto/QryAnswerSubmitterDTO.java, src/main/java/org/triumers/kmsback/quiz/query/dto/QryQuizDTO.java, src/main/java/org/triumers/kmsback/quiz/query/repository/AnswerSubmitterMapper.java, src/main/java/org/triumers/kmsback/quiz/query/service/QryAnswerSubmitterService.java, src/main/java/org/triumers/kmsback/quiz/query/service/QryAnswerSubmitterServiceImpl.java, src/main/java/org/triumers/kmsback/quiz/query/service/QryQuizServiceImpl.java, src/main/resources/org/triumers/kmsback/quiz/query/repository/AnswerSubmitterMapper.xml, src/test/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceTests.java, src/test/java/org/triumers/kmsback/post/command/Application/service/CmdTabServiceTests.java, src/test/java/org/triumers/kmsback/quiz/command/Application/service/CmdQuizServiceImplTest.java, src/test/java/org/triumers/kmsback/quiz/query/service/QryAnswerSubmitterServiceImplTest.java, src/test/java/org/triumers/kmsback/quiz/query/service/QryQuizServiceImplTest.java
=> [Feature] 퀴즈 기본 기능 구현

src/main/java/org/triumers/kmsback/auth/command/domain/aggregate/enums/UserRole.java, src/main/java/org/triumers/kmsback/common/config/SecurityConfig.java, src/test/java/org/triumers/kmsback/auth/command/Application/service/AuthServiceTest.java
계정의 권한에 따라 기능을 제한할 수 있는 기능이 구현되었습니다.
회원가입을 인사 권한 이상만 가능하도록 구현 후 작동까지(권한 있는 경우와 없는 경우 모두) 확인 완료되었습니다.
다만 현재는 개발의 편의성을 위해 전체 접근 권한 허용으로 해두었습니다.
=> [Feature] 권한 기능 구현

src/main/java/org/triumers/kmsback/auth/command/Application/service/AuthService.java, src/main/java/org/triumers/kmsback/auth/command/Application/service/AuthServiceImpl.java, src/main/java/org/triumers/kmsback/auth/command/domain/aggregate/entity/Auth.java, src/main/java/org/triumers/kmsback/common/config/SecurityConfig.java, src/main/java/org/triumers/kmsback/common/exception/WrongInputTypeException.java, src/test/java/org/triumers/kmsback/auth/command/Application/service/AuthServiceTest.java
회원 가입 시 다음과 같은 예외 처리가 구현되었습니다.
- 잘못된 이메일 예외 처리
- 잘못된 비밀번호 예외 처리
- 잘못된 이름 예외 처리
- 잘못된 휴대폰 번호 예외 처리
=> [Feature] 회원 가입 값에 대한 예외 처리 구현

src/main/java/org/triumers/kmsback/auth/command/Application/dto/PasswordDTO.java, src/main/java/org/triumers/kmsback/auth/command/Application/service/AuthService.java, src/main/java/org/triumers/kmsback/auth/command/Application/service/AuthServiceImpl.java, src/main/java/org/triumers/kmsback/common/exception/WrongInputValueException.java, src/test/java/org/triumers/kmsback/auth/command/Application/service/AuthServiceTest.java
현재 로그인한 계정에 대해 비밀번호를 변경하는 기능이 구현되었습니다.
=> [Feature] 비밀번호 변경 기능 구현

src/main/java/org/triumers/kmsback/employee/command/Application/dto/CmdEmployeeDTO.java, src/main/java/org/triumers/kmsback/employee/command/Application/service/CmdEmployeeService.java, src/main/java/org/triumers/kmsback/employee/command/Application/service/CmdEmployeeServiceImpl.java, src/main/java/org/triumers/kmsback/employee/command/domain/aggregate/entity/CmdEmployee.java, src/main/java/org/triumers/kmsback/employee/command/domain/repository/CmdEmployeeRepository.java
직원을 id, email, 이름으로 조회하는 기능이 구현되었습니다.
현재 기능은 타 서비스의 기능 구현을 위한 임시 구현으로 추후 좀 더 고도화 및 개선될 예정입니다.
=> [Feature] 직원 조회 기능(임시)

build.gradle, src/main/java/org/triumers/kmsback/post/command/Application/controller/CmdPostController.java, src/main/java/org/triumers/kmsback/post/command/Application/controller/CmdTabController.java, src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdJoinEmployeeDTO.java, src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdPostAndTagsDTO.java, src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdTabRelationDTO.java, src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostService.java, src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceImpl.java, src/main/java/org/triumers/kmsback/post/command/Application/service/CmdTabService.java, src/main/java/org/triumers/kmsback/post/command/Application/service/CmdTabServiceImpl.java, src/main/java/org/triumers/kmsback/post/command/Application/service/NotificationService.java, src/main/java/org/triumers/kmsback/post/command/domain/aggregate/entity/CmdPost.java, src/main/java/org/triumers/kmsback/post/query/controller/QryPostController.java, src/main/java/org/triumers/kmsback/post/query/dto/QryPostAndTagsDTO.java, src/main/java/org/triumers/kmsback/post/query/repository/QryPostMapper.java, src/main/java/org/triumers/kmsback/post/query/service/QryPostService.java, src/main/java/org/triumers/kmsback/post/query/service/QryPostServiceImpl.java, src/main/resources/org/triumers/kmsback/post/query/repository/QryPostMapper.xml, src/test/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceTests.java, src/test/java/org/triumers/kmsback/post/command/Application/service/CmdTabServiceTests.java, src/test/java/org/triumers/kmsback/post/query/service/QryPostServiceTest.java
- 게시글, 탭 컨트롤러 추가
- 게시글 히스토리, 좋아요 리스트 조회(추후 회원 정보 추가 필요)
- cmd 컨트롤러 테스트 완료
- 게시글 관련 조회 테스트 완료
=> [Feat] POST 컨트롤러 추가 및 게시글 관련 조회 기능 추가

src/main/java/org/triumers/kmsback/quiz/command/Application/dto/CmdQuizDTO.java, src/main/java/org/triumers/kmsback/quiz/command/Application/service/CmdQuizServiceImpl.java, src/main/java/org/triumers/kmsback/quiz/command/domain/aggregate/entity/CmdQuiz.java, src/main/java/org/triumers/kmsback/quiz/command/domain/aggregate/vo/CmdRequestQuizVo.java, src/main/java/org/triumers/kmsback/quiz/query/aggregate/entity/QryQuiz.java, src/main/java/org/triumers/kmsback/quiz/query/dto/QryQuizDTO.java, src/main/java/org/triumers/kmsback/quiz/query/service/QryQuizServiceImpl.java, src/main/resources/org/triumers/kmsback/quiz/query/repository/QuizMapper.xml, src/test/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceTests.java, src/test/java/org/triumers/kmsback/post/command/Application/service/CmdTabServiceTests.java, src/test/java/org/triumers/kmsback/post/query/service/QryPostServiceTest.java, src/test/java/org/triumers/kmsback/quiz/query/service/QryAnswerSubmitterServiceImplTest.java, src/test/java/org/triumers/kmsback/quiz/query/service/QryQuizServiceImplTest.java
feat/quiz -> dev
DB 수정에 따라 TOP_TAP_ID -> TAP_ID로 변경하였습니다.
=> [Refactor] DB수정에 따른 퀴즈 기능 수정

src/main/java/org/triumers/kmsback/group/query/controller/QryGroupController.java, src/main/java/org/triumers/kmsback/group/query/dto/QryGroupDTO.java, src/main/java/org/triumers/kmsback/group/query/repository/GroupMapper.java, src/main/java/org/triumers/kmsback/group/query/service/QryGroupService.java, src/main/java/org/triumers/kmsback/group/query/service/QryGroupServiceImpl.java, src/main/resources/org/triumers/kmsback/group/query/repository/GroupMapper.xml, src/test/java/org/triumers/kmsback/group/query/service/QryGroupServiceTest.java
feat/group -> dev
- 사원 번호로 속한 그룹정보 조회기능을 추가했습니다.
=> [Feature] 그룹 조회 기능

src/main/java/org/triumers/kmsback/auth/command/Application/controller/AuthController.java, src/main/java/org/triumers/kmsback/auth/command/domain/aggregate/vo/CmdRequestAuthVO.java, src/main/java/org/triumers/kmsback/auth/command/domain/aggregate/vo/CmdRequestEditMyInfoVO.java, src/main/java/org/triumers/kmsback/auth/command/domain/aggregate/vo/CmdRequestEditPasswordVO.java, src/main/java/org/triumers/kmsback/common/util/RegularExpression.java
비밀번호 변경, 내 정보 변경에 대한 Controller이 구현되었습니다.
이전 테스트 모두 통과하는 것 확인 완료
=> [Feature] 비밀번호 변경, 내 정보 변경 Controller 구현

build.gradle, src/main/java/org/triumers/kmsback/common/config/AwsS3Config.java, src/main/java/org/triumers/kmsback/common/exception/AwsS3Exception.java, src/main/java/org/triumers/kmsback/common/s3/controller/AwsS3Controller.java, src/main/java/org/triumers/kmsback/common/s3/service/AwsS3Service.java, src/main/java/org/triumers/kmsback/common/s3/service/AwsS3ServiceImpl.java
AWS S3에 파일을 업로드할 수 있는 기능이 구현되었습니다.
PostMan을 이용한 테스트 완료했습니다.
=> [Feature] AWS S3 파일 업로드 기능 구현

src/main/java/org/triumers/kmsback/quiz/query/aggregate/entity/QryAnswerSubmitter.java, src/main/java/org/triumers/kmsback/quiz/query/controller/QryAnswerSubmitterController.java, src/main/java/org/triumers/kmsback/quiz/query/dto/QryAnswerSubmitterDTO.java, src/main/java/org/triumers/kmsback/quiz/query/repository/AnswerSubmitterMapper.java, src/main/java/org/triumers/kmsback/quiz/query/service/QryAnswerSubmitterService.java, src/main/java/org/triumers/kmsback/quiz/query/service/QryAnswerSubmitterServiceImpl.java, src/main/resources/org/triumers/kmsback/quiz/query/repository/AnswerSubmitterMapper.xml, src/test/java/org/triumers/kmsback/quiz/query/service/QryAnswerSubmitterServiceImplTest.java
feat/quiz -> dev
사원 ID로 답 제출내역 조회기능을 추가하였습니다.
테스트 패스 확인되었습니다.
=> [Feature] 사원 ID로 제출내역 조회

build.gradle, src/main/java/org/triumers/kmsback/common/translation/controller/PostController.java, src/main/java/org/triumers/kmsback/common/translation/dto/PostDTO.java, src/main/java/org/triumers/kmsback/common/translation/entity/Post.java, src/main/java/org/triumers/kmsback/common/translation/entity/PostCn.java, src/main/java/org/triumers/kmsback/common/translation/entity/PostEng.java, src/main/java/org/triumers/kmsback/common/translation/entity/PostJpn.java, src/main/java/org/triumers/kmsback/common/translation/repository/PostRepository.java, src/main/java/org/triumers/kmsback/common/translation/service/DeeplService.java, src/main/java/org/triumers/kmsback/common/translation/service/DeeplServiceImpl.java, src/main/java/org/triumers/kmsback/common/translation/service/PostService.java, src/main/java/org/triumers/kmsback/common/translation/service/PostServiceImpl.java, src/test/java/org/triumers/kmsback/common/translation/service/DeeplServiceImplTests.java, src/test/java/org/triumers/kmsback/common/translation/service/PostServiceImplTests.java
feat/translation -> dev
- 게시글 제목, 내용 영어, 중국어, 일본어로 번역하는 기능 구현
- 번역 누를 시에 번역 db에 이미 번역된 글 있는지 확인, 없으면 번역한 후 db에 저장한 후 불러옴
- db에 이미 있을 경우 이미 저장된 글 불러옴
=> [Feature] 게시글 번역 기능 구현

src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdPostAndTagsDTO.java, src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdPostDTO.java, src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceImpl.java, src/main/java/org/triumers/kmsback/post/command/domain/aggregate/entity/CmdPost.java, src/main/java/org/triumers/kmsback/post/query/aggregate/entity/QryPost.java, src/main/java/org/triumers/kmsback/post/query/aggregate/entity/QryPostAndTag.java, src/main/java/org/triumers/kmsback/post/query/dto/QryPostAndTagsDTO.java, src/main/java/org/triumers/kmsback/post/query/dto/QryPostDTO.java, src/main/java/org/triumers/kmsback/post/query/service/QryPostServiceImpl.java, src/main/resources/org/triumers/kmsback/post/query/repository/QryPostMapper.xml, src/test/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceTests.java, src/test/java/org/triumers/kmsback/post/query/service/QryPostServiceTest.java
- post 테이블에 img추가에 따라 게시글 관련 기능 수정
- 게시글 cmd/query 테스트 완료
=> [Style] postImg 추가 및 관련 기능 코드 수정

src/main/java/org/triumers/kmsback/quiz/query/controller/QryAnswerSubmitterController.java, src/main/java/org/triumers/kmsback/quiz/query/controller/QryQuizController.java, src/main/resources/org/triumers/kmsback/quiz/query/repository/AnswerSubmitterMapper.xml, src/main/resources/org/triumers/kmsback/quiz/query/repository/QuizMapper.xml, src/test/java/org/triumers/kmsback/KmsBackApplicationTests.java
feat/quiz -> dev
- Controller에서 Mapping 경로를 수정했습니다.
- 매개변수에 @PathVariable을 추가하였습니다.
=> [Feature] quiz mapper 수정 및 PathVariable 추가

src/main/java/org/triumers/kmsback/common/config/SecurityConfig.java, src/main/java/org/triumers/kmsback/common/s3/service/AwsS3ServiceImpl.java, src/main/java/org/triumers/kmsback/user/command/Application/controller/CmdDutyController.java, src/main/java/org/triumers/kmsback/user/command/Application/dto/CmdPositionDTO.java, src/main/java/org/triumers/kmsback/user/command/Application/dto/CmdRankDTO.java, src/main/java/org/triumers/kmsback/user/command/Application/service/CmdDutyService.java, src/main/java/org/triumers/kmsback/user/command/Application/service/CmdDutyServiceImpl.java, src/main/java/org/triumers/kmsback/user/command/domain/aggregate/entity/CmdPosition.java, src/main/java/org/triumers/kmsback/user/command/domain/aggregate/entity/CmdRank.java, src/main/java/org/triumers/kmsback/user/command/domain/aggregate/vo/CmdRequestDutyVO.java, src/main/java/org/triumers/kmsback/user/command/domain/repository/PositionRepository.java, src/main/java/org/triumers/kmsback/user/command/domain/repository/RankRepository.java, src/main/java/org/triumers/kmsback/user/query/aggregate/entity/QryPosition.java, src/main/java/org/triumers/kmsback/user/query/aggregate/entity/QryRank.java, src/main/java/org/triumers/kmsback/user/query/aggregate/vo/QryPositionVO.java, src/main/java/org/triumers/kmsback/user/query/aggregate/vo/QryRankVO.java, src/main/java/org/triumers/kmsback/user/query/aggregate/vo/QryResponsePositionListVO.java, src/main/java/org/triumers/kmsback/user/query/aggregate/vo/QryResponseRankListVO.java, src/main/java/org/triumers/kmsback/user/query/controller/QryDutyController.java, src/main/java/org/triumers/kmsback/user/query/dto/QryPositionDTO.java, src/main/java/org/triumers/kmsback/user/query/dto/QryRankDTO.java, src/main/java/org/triumers/kmsback/user/query/repository/DutyMapper.java, src/main/java/org/triumers/kmsback/user/query/service/QryDutyService.java, src/main/java/org/triumers/kmsback/user/query/service/QryDutyServiceImpl.java, src/main/resources/org/triumers/kmsback/user/query/repository/DutyMapper.xml, src/test/java/org/triumers/kmsback/user/command/Application/service/CmdDutyServiceTest.java, src/test/java/org/triumers/kmsback/user/query/service/QryDutyServiceTest.java
feat/manager -> dev
직급, 직책 CRUD 기능이 구현되었습니다.
이젠.. 정말 직원 테이블 건들 수 있겠죠?
=> [Feature] 직급, 직책 CRUD 기능 구현

src/main/java/org/triumers/kmsback/post/command/Application/controller/CmdPostController.java, src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdPostDTO.java, src/main/java/org/triumers/kmsback/post/command/domain/aggregate/vo/CmdRequestPost.java, src/main/java/org/triumers/kmsback/post/query/aggregate/entity/QryPost.java, src/main/java/org/triumers/kmsback/post/query/aggregate/entity/QryPostAndTag.java, src/main/java/org/triumers/kmsback/post/query/controller/QryPostController.java, src/main/java/org/triumers/kmsback/post/query/dto/QryPostAndTagsDTO.java, src/main/java/org/triumers/kmsback/post/query/dto/QryPostDTO.java, src/main/java/org/triumers/kmsback/post/query/service/QryPostServiceImpl.java, src/main/java/org/triumers/kmsback/tab/command/Application/controller/CmdTabController.java, src/main/resources/org/triumers/kmsback/post/query/repository/QryPostMapper.xml
feat/post-> dev
- 게시글을 조회할 경우, 좋아요 리스트도 함께 반환하도록 코드 수정
- date -> datetime으로 수정
- 컨트롤러 수정
테스트 모두 통과되었습니다!
=> [Feature] 게시글 조회 시, 좋아요 리스트 추가 

src/main/java/org/triumers/kmsback/anonymousboard/query/service/QryAnonymousBoardServiceImpl.java, src/test/java/org/triumers/kmsback/anonymousboard/query/service/QryAnonymousBoardCommentServiceImplTests.java, src/test/java/org/triumers/kmsback/anonymousboard/query/service/QryAnonymousBoardServiceImplTests.java
feat/anonymous-board -> dev
- 테스트 코드 수정
- 페이징 처리를 위해 코드 수정
=> [Refactor] 익명게시판 테스트 코드 수정 및 페이징 처리

src/test/java/org/triumers/kmsback/group/query/service/QryGroupServiceTest.java
- db 카테고리 값 변경 및 테스트 값 변경
전체 테스트 통과 했습니다!
=> [Refactor] 그룹 데이터 값 변경

src/main/java/org/triumers/kmsback/user/query/aggregate/entity/QryEmployee.java, src/main/java/org/triumers/kmsback/user/query/dto/QryEmployeeDTO.java, src/main/java/org/triumers/kmsback/user/query/repository/EmployeeMapper.java, src/main/java/org/triumers/kmsback/user/query/service/QryEmployeeService.java, src/main/java/org/triumers/kmsback/user/query/service/QryEmployeeServiceImpl.java, src/main/resources/org/triumers/kmsback/user/query/repository/EmployeeMapper.xml, src/test/java/org/triumers/kmsback/user/query/service/QryEmployeeServiceTest.java
feat/employee -> dev
직원을 조회하는 기능이 구현되었습니다.
=> [Feature] 직원 조회 기능 구현

src/main/java/org/triumers/kmsback/anonymousboard/query/controller/QryAnonymousBoardCommentController.java, src/main/java/org/triumers/kmsback/anonymousboard/query/service/QryAnonymousBoardCommentService.java, src/main/java/org/triumers/kmsback/anonymousboard/query/service/QryAnonymousBoardCommentServiceImpl.java, src/test/java/org/triumers/kmsback/anonymousboard/query/service/QryAnonymousBoardCommentServiceImplTests.java
feat/anonymous-board -> dev
- 댓글 개수 반환하는 기능 구현
=> [Feature] 익명게시판 댓글 개수 반환 기능 구현

src/main/java/org/triumers/kmsback/group/query/repository/GroupMapper.java, src/main/java/org/triumers/kmsback/group/query/service/QryGroupService.java, src/main/java/org/triumers/kmsback/group/query/service/QryGroupServiceImpl.java, src/main/java/org/triumers/kmsback/post/query/aggregate/vo/QryRequestPost.java, src/main/java/org/triumers/kmsback/post/query/controller/QryPostController.java, src/main/java/org/triumers/kmsback/post/query/repository/QryPostMapper.java, src/main/java/org/triumers/kmsback/post/query/service/QryPostService.java, src/main/java/org/triumers/kmsback/post/query/service/QryPostServiceImpl.java, src/main/resources/org/triumers/kmsback/group/query/repository/GroupMapper.xml, src/main/resources/org/triumers/kmsback/post/query/repository/QryPostMapper.xml, src/test/java/org/triumers/kmsback/post/query/service/QryPostServiceTest.java
- 회원이 접근 가능한 모든 탭id(public 포함) 조회 
- 회원이 접근 가능한 전체 게시글에서 검색 및 조회 기능 추가
=> [Feature] 회원이 접근 가능한 전체 게시글에서 검색 및 조회

src/main/java/org/triumers/kmsback/organization/query/aggregate/vo/QryCenterVO.java, src/main/java/org/triumers/kmsback/organization/query/aggregate/vo/QryDepartmentVO.java, src/main/java/org/triumers/kmsback/organization/query/aggregate/vo/QryRequestSearchNameVO.java, src/main/java/org/triumers/kmsback/organization/query/aggregate/vo/QryTeamMemberVO.java, src/main/java/org/triumers/kmsback/organization/query/aggregate/vo/QryTeamVO.java, src/main/java/org/triumers/kmsback/organization/query/controller/OrganizationController.java, src/main/java/org/triumers/kmsback/organization/query/dto/QryCenterDTO.java, src/main/java/org/triumers/kmsback/organization/query/dto/QryDepartmentDTO.java, src/main/java/org/triumers/kmsback/organization/query/dto/QryTeamDTO.java, src/main/java/org/triumers/kmsback/organization/query/repository/OrganizationMapper.java, src/main/java/org/triumers/kmsback/organization/query/service/QryCenterService.java, src/main/java/org/triumers/kmsback/organization/query/service/QryCenterServiceImpl.java, src/main/java/org/triumers/kmsback/organization/query/service/QryDepartmentService.java, src/main/java/org/triumers/kmsback/organization/query/service/QryDepartmentServiceImpl.java, src/main/java/org/triumers/kmsback/organization/query/service/QryTeamService.java, src/main/java/org/triumers/kmsback/organization/query/service/QryTeamServiceImpl.java, src/main/java/org/triumers/kmsback/user/query/repository/EmployeeMapper.java, src/main/java/org/triumers/kmsback/user/query/service/QryEmployeeService.java, src/main/java/org/triumers/kmsback/user/query/service/QryEmployeeServiceImpl.java, src/main/resources/org/triumers/kmsback/organization/query/repository/OrganizationMapper.xml, src/main/resources/org/triumers/kmsback/user/query/repository/EmployeeMapper.xml, src/test/java/org/triumers/kmsback/organization/query/service/QryTeamServiceTest.java, src/test/java/org/triumers/kmsback/user/query/service/QryEmployeeServiceTest.java
feat/organization -> dev
본부, 부서, 팀 조회 기능이 구현되었습니다.
id, 이름, 상위 id 등을 이용해 조회가 가능하며, 하위 객체를 포함하는 조회와 단순 조회를 나누어 구현했습니다.
=> [Feature] 본부, 부서, 팀 조회 기능 구현

src/main/resources/org/triumers/kmsback/anonymousboard/query/repository/QryAnonymousBoardMapper.xml
feat/anonymous-board -> dev
- 프론트 연결하고 검색할 때 페이징 처리가 되지 않는 부분 수정
=> [Refactor] 페이징 처리 코드 수정

src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceImpl.java, src/main/java/org/triumers/kmsback/post/query/controller/QryPostController.java, src/main/java/org/triumers/kmsback/post/query/dto/QryPostAndTagsDTO.java, src/main/java/org/triumers/kmsback/post/query/repository/QryPostMapper.java, src/main/java/org/triumers/kmsback/post/query/service/QryPostService.java, src/main/java/org/triumers/kmsback/post/query/service/QryPostServiceImpl.java, src/main/resources/org/triumers/kmsback/post/query/repository/QryPostMapper.xml, src/test/java/org/triumers/kmsback/post/query/service/QryPostServiceTest.java
- 사용자 id로 작성한 게시글 조회
- 사용자 id로 좋아요한 게시글 조회
- 사용자 id로 즐겨찾기한 게시글 조회
- 게시글 id에 대한 사용자 좋아요/즐겨찾기 여부 조회
전체 테스트 통과
=> [Feature] 사용자 관련 게시글 조회 기능

src/main/java/org/triumers/kmsback/user/query/aggregate/vo/QryResponseDocsVO.java, src/main/java/org/triumers/kmsback/user/query/controller/QryAuthController.java, src/main/java/org/triumers/kmsback/user/query/controller/QryController.java, src/main/java/org/triumers/kmsback/user/query/dto/QryDocsDTO.java, src/main/java/org/triumers/kmsback/user/query/service/QryAuthService.java, src/main/java/org/triumers/kmsback/user/query/service/QryAuthServiceImpl.java, src/test/java/org/triumers/kmsback/user/query/service/QryAuthServiceTest.java
feat/organization -> dev
내가 작성한 게시글 조회 기능 구현
내가 작성한 댓글 조회 기능 구현
내가 즐겨찾기에 등록한 게시글 조회 구현
내가 좋아요한 게시글 조회 구현
=> [Feature] 내 게시물, 댓글, 즐겨찾기, 좋아요한 게시물 조회 기능 구현

src/main/java/org/triumers/kmsback/group/query/controller/QryGroupController.java, src/main/java/org/triumers/kmsback/group/query/dto/QryGroupDTO.java, src/main/java/org/triumers/kmsback/group/query/service/QryGroupService.java, src/main/java/org/triumers/kmsback/group/query/service/QryGroupServiceImpl.java, src/main/java/org/triumers/kmsback/post/command/Application/controller/CmdPostController.java, src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdFavoritesDTO.java, src/main/java/org/triumers/kmsback/post/command/Application/dto/CmdLikeDTO.java, src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceImpl.java, src/main/java/org/triumers/kmsback/post/query/controller/QryPostController.java, src/main/java/org/triumers/kmsback/post/query/dto/QryPostAndTagsDTO.java, src/main/java/org/triumers/kmsback/post/query/repository/QryPostMapper.java, src/main/java/org/triumers/kmsback/post/query/service/QryPostService.java, src/main/java/org/triumers/kmsback/post/query/service/QryPostServiceImpl.java, src/main/resources/org/triumers/kmsback/post/query/repository/QryPostMapper.xml, src/test/java/org/triumers/kmsback/group/query/service/QryGroupServiceTest.java
- 회원이 속한 탭 조회 params 삭제 및 whoAmI() 사용으로 변경
=> [Refactor] 회원이 속한 탭 조회 코드 변경

src/main/java/org/triumers/kmsback/user/query/aggregate/vo/QryRequestEmployeeVO.java, src/main/java/org/triumers/kmsback/user/query/aggregate/vo/QryResponseEmployeeVO.java, src/main/java/org/triumers/kmsback/user/query/controller/QryEmployeeController.java
feat/employee -> dev
직원을 조회하는 기능 Controller가 구현되었습니다.
- 직원 Id 조회
- 전체 조회
- 이메일 조회
- 이름 조회
- 팀 Id 조회
=> [Feature] 직원 조회 Controller 구현

.github/workflows/deploy.yml, Dockerrun.aws.json, Procfile, build.gradle, elasticbeanstalk/docker-compose.yml
deploy -> dev
Elastic Beanstalk에 배포된 Docker 컨테이너에 자동 배포 되도록 설정하였습니다.
=> [Deploy] Main에 이벤트 발생 시, 자동 배포 코드 작성 및 Docker 환경파일 생성

src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceImpl.java, src/main/java/org/triumers/kmsback/tab/command/Application/controller/CmdTabController.java
feat/post-> dev
- 포스트 등록 시, 서비스에서 date 추가
- 탭 컨트롤러 param 추가
=> [Refactor] 탭/포스트 서비스 및 컨트롤러 수정

src/main/java/org/triumers/kmsback/post/query/aggregate/vo/QryRequestPost.java, src/main/java/org/triumers/kmsback/post/query/controller/QryPostController.java, src/main/resources/org/triumers/kmsback/post/query/repository/QryPostMapper.xml
feat/post-> dev
- requestDTO 수정 및 pageable 삭제
- 포스트 로딩 순서 변경(DESC)
=> [Refactor] 페이징 처리에 따른 컨트롤러 수정

src/main/java/org/triumers/kmsback/common/config/SecurityConfig.java, src/main/java/org/triumers/kmsback/common/controller/StatusCheckController.java, src/main/java/org/triumers/kmsback/common/exception/AwsS3Exception.java, src/main/java/org/triumers/kmsback/common/s3/controller/AwsS3Controller.java, src/main/java/org/triumers/kmsback/common/s3/service/AwsS3Service.java, src/main/java/org/triumers/kmsback/common/s3/service/AwsS3ServiceImpl.java, src/main/java/org/triumers/kmsback/common/util/IpAddressUtil.java
이미지만 업로드 가능하게 하는 기능이 구현되었습니다.
추후 2차 인증 로직 고도화를 위한 접속 IP 확인 기능이 구현되었습니다.
개발이 어느정도 안정화 되고 있음에 따라 전 경로 permitAll 을 해제했습니다.
=> [Feature] 이미지 한정 업로드, 접속 IP확인 기능 구현

src/main/java/org/triumers/kmsback/quiz/query/controller/QryQuizController.java, src/main/java/org/triumers/kmsback/quiz/query/service/QryQuizServiceImpl.java
원치 않는 에러로 인해 작동하지 않는 경우에 대한 에러 처리가 추가되었습니다.
hotfix -> dev
퀴즈 요청 시 에러가 터지는 것을 처리했습니다.
=> [Fix] 에러 처리 구현

src/main/java/org/triumers/kmsback/common/auth/LoginFilter.java, src/main/java/org/triumers/kmsback/user/command/Application/controller/AuthController.java
이제 등록 여부가 아닌 사내망, 외부망 여부에 따라 2차 인증을 요구하도록 구현했습니다.
외부망 접속 시 2차 인증을 강제하는 기능이 구현되었습니다.
=> [Feature] 외부망 접속 시 2차 인증 요구 기능 구현

src/main/java/org/triumers/kmsback/common/controller/StatusCheckController.java
hotfix -> main
현재 접속 및 값 제대로 꺼내오는지 확인하는 임시 컨트롤러
=> [Fix] 외부망 접속 시 2차 인증 버그 수정위한 컨트롤러

src/main/java/org/triumers/kmsback/common/auth/LoginFilter.java
hotfix -> main
로그인 필터에 결과 확인을 위한 프린트문 추가
=> [Fix] 임시 프린트문 생성

src/main/java/org/triumers/kmsback/post/command/Application/service/CmdPostServiceImpl.java, src/main/java/org/triumers/kmsback/tab/command/Application/service/CmdTabServiceImpl.java, src/main/java/org/triumers/kmsback/tab/command/domain/repository/CmdTabRelationRepository.java, src/main/resources/org/triumers/kmsback/group/query/repository/GroupMapper.xml
- 기존 사용자가 속한 워크스페이스의 탭은 joinEmployee에 등록되지 않아 불러오지 못하던 부분을 개선하여, 팀id가 속한 워크스페이스를 자동으로 추가 조회 하도록 수정
- 탭 직원/새로운 탭 중복 처리 
- 공백 제거 되었던 오류 수정 
전체 테스트 통과 했습니다!
=> [Refactor] 회원의 워크스페이스 추가로 조회해오기  

src/main/java/org/triumers/kmsback/anonymousboard/command/Application/controller/CmdAnonymousBoardCommentController.java, src/main/java/org/triumers/kmsback/anonymousboard/command/Application/controller/CmdAnonymousBoardController.java, src/main/java/org/triumers/kmsback/anonymousboard/query/controller/QryAnonymousBoardCommentController.java, src/main/java/org/triumers/kmsback/anonymousboard/query/controller/QryAnonymousBoardController.java, src/main/java/org/triumers/kmsback/approval/command/Application/controller/CmdRequestApprovalController.java, src/main/java/org/triumers/kmsback/approval/query/controller/QryRequestApprovalController.java, src/main/java/org/triumers/kmsback/comment/command/Application/controller/CommentController.java, src/main/java/org/triumers/kmsback/comment/query/controller/QryCommentController.java, src/main/java/org/triumers/kmsback/common/auth/authenticator/controller/OTPUserController.java, src/main/java/org/triumers/kmsback/common/controller/StatusCheckController.java, src/main/java/org/triumers/kmsback/common/s3/controller/AwsS3Controller.java, src/main/java/org/triumers/kmsback/common/translation/controller/PostController.java, src/main/java/org/triumers/kmsback/group/query/controller/QryGroupController.java, src/main/java/org/triumers/kmsback/organization/query/controller/OrganizationController.java, src/main/java/org/triumers/kmsback/post/command/Application/controller/CmdPostController.java, src/main/java/org/triumers/kmsback/post/query/controller/QryPostController.java, src/main/java/org/triumers/kmsback/quiz/command/Application/controller/CmdAnswerSubmitterController.java, src/main/java/org/triumers/kmsback/quiz/command/Application/controller/CmdQuizController.java, src/main/java/org/triumers/kmsback/quiz/query/controller/QryAnswerSubmitterController.java, src/main/java/org/triumers/kmsback/tab/command/Application/controller/CmdTabController.java, src/main/java/org/triumers/kmsback/user/command/Application/controller/AuthController.java, src/main/java/org/triumers/kmsback/user/command/Application/controller/CmdDutyController.java, src/main/java/org/triumers/kmsback/user/command/Application/controller/ManagerController.java, src/main/java/org/triumers/kmsback/user/query/controller/QryDutyController.java
exception-handling -> dev
예외 처리가 따로 되어있지 않은 경우가 있어 남은 기한을 고려, 우선 임시 조치를 해두었습니다. 추후 이 버전에서 변경된 점은 원복시키며 각 예외 상황에 적합한 동작을 수행하도록 개선할 예정입니다.
=> [Fix] 예외 처리 임시 구현

src/main/resources/org/triumers/kmsback/group/query/repository/GroupMapper.xml
- JOIN 오류로 워크스페이스를 조회해오지 못한 부분을 수정했습니다.
=> [Bug] 워크스페이스 추가 조회 수정
